version: '3'
services:
  my-app:
    container_name: my-app
    image: localhost:8083/my-app:2.1
    ports:
      - 3000:3000
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Vlad0486!
    volumes:
      - mongo-data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Vlad0486!
      - ME_CONFIG_MONGODB_SERVER=mongodb
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 8083:8083
    volumes:
      - nexus-data:/nexus-data
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_WHICH}:/usr/bin/docker
volumes:
  mongo-data:
    driver: local
  nexus-data:
    driver: local
  jenkins_home:
    driver: local
